// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwkPF7xWSrjyqiVYxHUFmTjnoE6dbivuI',
    appId: '1:398821848013:web:0328750778a185917c4a84',
    messagingSenderId: '398821848013',
    projectId: 'pharmatech-d7beb',
    authDomain: 'pharmatech-d7beb.firebaseapp.com',
    storageBucket: 'pharmatech-d7beb.appspot.com',
    measurementId: 'G-QXSJVKKESK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfALXSa8w9Jei0rvTp0cSCyXm_OV4MXAU',
    appId: '1:398821848013:android:88b2a897772984bb7c4a84',
    messagingSenderId: '398821848013',
    projectId: 'pharmatech-d7beb',
    storageBucket: 'pharmatech-d7beb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9FnmYJSJD_HxFjPVSaXVITlNHc7vpkXc',
    appId: '1:398821848013:ios:968dd48cccd841e17c4a84',
    messagingSenderId: '398821848013',
    projectId: 'pharmatech-d7beb',
    storageBucket: 'pharmatech-d7beb.appspot.com',
    iosClientId: '398821848013-0dcts75uaumg136d6ts4tfbioh9p5gpv.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalyearproject',
  );
}
